sonar.organization=ichsanmldni
sonar.projectKey=ichsanmldni_simpel-upnvj-vuln
sonar.projectName=simpel-upnvj
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/public/css/**,**/public/js/**,**/public/img/**
