sonar.organization=GANTI-organization-key-kamu
sonar.projectKey=GANTI-project-key-kamu
sonar.projectName=simpel-upnvj
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/public/css/**,**/public/js/**,**/public/img/**
